---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - /home/jayson/plex_media/tvseries:/tv
      - /home/jayson/plex_media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
